#!/usr/bin/env bash
# wf-step-agents.sh — Single source of truth for the PHASE:STEP -> wf agent role mapping.
#
# Sourced by:
#   - scripts/wf-orchestrate.sh (legacy historical enforcement, now off-loaded to the hook)
#   - hooks/wf-auth.sh  (identity enforcement via PreToolUse)
#
# Do not duplicate these values elsewhere. Any change goes through this file.
# Key = "PHASE:STEP" (composite), value = expected wf role.

declare -gA STEP_AGENT=(
  # BOOTSTRAP
  ["BOOTSTRAP:DETERMINE_NAME"]="pm"
  ["BOOTSTRAP:RUN_BOOTSTRAP"]="pm"
  ["BOOTSTRAP:STORE_PATH"]="pm"
  ["BOOTSTRAP:COLLECT_CARD_NUM"]="pm"
  ["BOOTSTRAP:COLLECT_BRANCH_TYPE"]="pm"
  ["BOOTSTRAP:CREATE_BRANCH_Q"]="pm"
  ["BOOTSTRAP:SPAWN_TEAM"]="pm"
  # REQUIREMENTS
  ["REQUIREMENTS:COLLECT_PRD"]="po"
  ["REQUIREMENTS:GENERATE_PRD"]="po"
  ["REQUIREMENTS:CHECKPOINT_REQ"]="pm"
  # FUNCTIONAL_SPECS
  ["FUNCTIONAL_SPECS:INTERVIEW_SPECS"]="po"
  ["FUNCTIONAL_SPECS:GENERATE_SPECS"]="po"
  ["FUNCTIONAL_SPECS:GENERATE_ACCEPTANCE"]="po"
  ["FUNCTIONAL_SPECS:VALIDATE_SPECS"]="or"
  ["FUNCTIONAL_SPECS:CHECKPOINT_FUNC"]="pm"
  # TECHNICAL_DESIGN
  ["TECHNICAL_DESIGN:GENERATE_DESIGN"]="tl"
  ["TECHNICAL_DESIGN:CHECKPOINT_DESIGN"]="pm"
  # REVIEW
  ["REVIEW:RV_REVIEW"]="rv"
  ["REVIEW:CHECK_EXIT"]="or"
  ["REVIEW:ANTI_LOOP"]="or"
  ["REVIEW:DISPATCH"]="or"
  ["REVIEW:PO_UPDATE"]="po"
  ["REVIEW:TL_UPDATE"]="tl"
  ["REVIEW:UPDATE_TRACKING"]="or"
  # PLANNING
  ["PLANNING:GENERATE_TASKS"]="tl"
  ["PLANNING:ASSIGN_WORKTREES"]="tl"
  ["PLANNING:CHECKPOINT_TASKS"]="pm"
  # IMPLEMENTATION
  ["IMPLEMENTATION:DV_IMPLEMENT"]="or"
  ["IMPLEMENTATION:TL_SUPERVISE"]="tl"
  ["IMPLEMENTATION:CHECKPOINT_IMPL"]="pm"
  ["IMPLEMENTATION:MERGE_WORKTREES"]="pm"
  # CODE_REVIEW
  ["CODE_REVIEW:TL_REVIEW"]="tl"
  ["CODE_REVIEW:CHECK_CR_EXIT"]="or"
  ["CODE_REVIEW:DV_FIX"]="dv"
  ["CODE_REVIEW:UPDATE_TRACKING_CR"]="or"
  # VALIDATION
  ["VALIDATION:PO_VALIDATE"]="qa"
  ["VALIDATION:QA_ACCEPTANCE_TEST"]="qa"
  ["VALIDATION:HO_VALIDATE"]="pm"
  ["VALIDATION:CHECKPOINT_VALID"]="pm"
  # CLOSURE
  ["CLOSURE:CLEANUP_WORKTREES"]="pm"
  ["CLOSURE:COMMIT"]="pm"
  ["CLOSURE:PUSH"]="pm"
  ["CLOSURE:PR_CREATE"]="pm"
  ["CLOSURE:HO_MERGE"]="pm"
  ["CLOSURE:BILAN"]="pm"
  ["CLOSURE:LOG_AUDIT"]="or"
  ["CLOSURE:CLEANUP"]="pm"
  ["CLOSURE:ARCHIVE"]="pm"
  ["CLOSURE:PR_TRIAGE"]="pm"
)

# Reverse index STEP -> PHASE to resolve legacy calls passing STEP alone.
declare -gA STEP_PHASE=(
  ["DETERMINE_NAME"]="BOOTSTRAP"
  ["RUN_BOOTSTRAP"]="BOOTSTRAP"
  ["STORE_PATH"]="BOOTSTRAP"
  ["COLLECT_CARD_NUM"]="BOOTSTRAP"
  ["COLLECT_BRANCH_TYPE"]="BOOTSTRAP"
  ["CREATE_BRANCH_Q"]="BOOTSTRAP"
  ["SPAWN_TEAM"]="BOOTSTRAP"
  ["COLLECT_PRD"]="REQUIREMENTS"
  ["GENERATE_PRD"]="REQUIREMENTS"
  ["CHECKPOINT_REQ"]="REQUIREMENTS"
  ["INTERVIEW_SPECS"]="FUNCTIONAL_SPECS"
  ["GENERATE_SPECS"]="FUNCTIONAL_SPECS"
  ["GENERATE_ACCEPTANCE"]="FUNCTIONAL_SPECS"
  ["VALIDATE_SPECS"]="FUNCTIONAL_SPECS"
  ["CHECKPOINT_FUNC"]="FUNCTIONAL_SPECS"
  ["GENERATE_DESIGN"]="TECHNICAL_DESIGN"
  ["CHECKPOINT_DESIGN"]="TECHNICAL_DESIGN"
  ["RV_REVIEW"]="REVIEW"
  ["CHECK_EXIT"]="REVIEW"
  ["ANTI_LOOP"]="REVIEW"
  ["DISPATCH"]="REVIEW"
  ["PO_UPDATE"]="REVIEW"
  ["TL_UPDATE"]="REVIEW"
  ["UPDATE_TRACKING"]="REVIEW"
  ["GENERATE_TASKS"]="PLANNING"
  ["ASSIGN_WORKTREES"]="PLANNING"
  ["CHECKPOINT_TASKS"]="PLANNING"
  ["DV_IMPLEMENT"]="IMPLEMENTATION"
  ["TL_SUPERVISE"]="IMPLEMENTATION"
  ["CHECKPOINT_IMPL"]="IMPLEMENTATION"
  ["MERGE_WORKTREES"]="IMPLEMENTATION"
  ["TL_REVIEW"]="CODE_REVIEW"
  ["CHECK_CR_EXIT"]="CODE_REVIEW"
  ["DV_FIX"]="CODE_REVIEW"
  ["UPDATE_TRACKING_CR"]="CODE_REVIEW"
  ["PO_VALIDATE"]="VALIDATION"
  ["QA_ACCEPTANCE_TEST"]="VALIDATION"
  ["HO_VALIDATE"]="VALIDATION"
  ["CHECKPOINT_VALID"]="VALIDATION"
  ["CLEANUP_WORKTREES"]="CLOSURE"
  ["COMMIT"]="CLOSURE"
  ["PUSH"]="CLOSURE"
  ["PR_CREATE"]="CLOSURE"
  ["HO_MERGE"]="CLOSURE"
  ["CLEANUP"]="CLOSURE"
  ["BILAN"]="CLOSURE"
  ["LOG_AUDIT"]="CLOSURE"
  ["ARCHIVE"]="CLOSURE"
  ["PR_TRIAGE"]="CLOSURE"
)
